/// Flutter icons PageIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PageIcons
///      fonts:
///       - asset: fonts/PageIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PageIcons {
  PageIcons._();

  static const _kFontFam = 'PageIcons';
  static const String? _kFontPkg = null;

  static const IconData book_shelf = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chandelier = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData armchair = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
